# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileRenamer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1183, 683)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.d_browse_frame = QtWidgets.QFrame(Form)
        self.d_browse_frame.setObjectName("d_browse_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.d_browse_frame)
        self.horizontalLayout.setContentsMargins(25, 0, -1, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.d_browse_frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.directory_name = QtWidgets.QLineEdit(self.d_browse_frame)
        self.directory_name.setObjectName("directory_name")
        self.horizontalLayout.addWidget(self.directory_name)
        self.btn_browse = QtWidgets.QPushButton(self.d_browse_frame)
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout.addWidget(self.btn_browse)
        self.verticalLayout_3.addWidget(self.d_browse_frame)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(25, -1, -1, -1)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.d_browse_frame_2 = QtWidgets.QFrame(Form)
        self.d_browse_frame_2.setObjectName("d_browse_frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.d_browse_frame_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.d_browse_frame_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.directory_name_output = QtWidgets.QLineEdit(self.d_browse_frame_2)
        self.directory_name_output.setObjectName("directory_name_output")
        self.horizontalLayout_9.addWidget(self.directory_name_output)
        self.btn_browse_output = QtWidgets.QPushButton(self.d_browse_frame_2)
        self.btn_browse_output.setObjectName("btn_browse_output")
        self.horizontalLayout_9.addWidget(self.btn_browse_output)
        self.verticalLayout_4.addWidget(self.d_browse_frame_2)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setStyleSheet("font: italic;\n"
"color: rgb(191, 191, 191);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setStyleSheet("font: italic;\n"
"color: rgb(191, 191, 191);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.chk_auto_rename = QtWidgets.QCheckBox(Form)
        self.chk_auto_rename.setObjectName("chk_auto_rename")
        self.horizontalLayout_8.addWidget(self.chk_auto_rename)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setStyleSheet("font: italic;\n"
"color: rgb(191, 191, 191);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chk_replace = QtWidgets.QCheckBox(Form)
        self.chk_replace.setObjectName("chk_replace")
        self.horizontalLayout_2.addWidget(self.chk_replace)
        self.replace_from = QtWidgets.QLineEdit(Form)
        self.replace_from.setEnabled(False)
        self.replace_from.setObjectName("replace_from")
        self.horizontalLayout_2.addWidget(self.replace_from)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.replace_to = QtWidgets.QLineEdit(Form)
        self.replace_to.setEnabled(False)
        self.replace_to.setObjectName("replace_to")
        self.horizontalLayout_2.addWidget(self.replace_to)
        self.chk_use_re = QtWidgets.QCheckBox(Form)
        self.chk_use_re.setEnabled(False)
        self.chk_use_re.setObjectName("chk_use_re")
        self.horizontalLayout_2.addWidget(self.chk_use_re)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setStyleSheet("font: italic;\n"
"color: rgb(191, 191, 191);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chk_replace2 = QtWidgets.QCheckBox(Form)
        self.chk_replace2.setObjectName("chk_replace2")
        self.horizontalLayout_7.addWidget(self.chk_replace2)
        self.replace_from2 = QtWidgets.QLineEdit(Form)
        self.replace_from2.setEnabled(False)
        self.replace_from2.setObjectName("replace_from2")
        self.horizontalLayout_7.addWidget(self.replace_from2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.replace_to2 = QtWidgets.QLineEdit(Form)
        self.replace_to2.setEnabled(False)
        self.replace_to2.setObjectName("replace_to2")
        self.horizontalLayout_7.addWidget(self.replace_to2)
        self.chk_use_re2 = QtWidgets.QCheckBox(Form)
        self.chk_use_re2.setEnabled(False)
        self.chk_use_re2.setObjectName("chk_use_re2")
        self.horizontalLayout_7.addWidget(self.chk_use_re2)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setStyleSheet("font: italic;\n"
"color: rgb(191, 191, 191);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chk_folderGRTS = QtWidgets.QCheckBox(Form)
        self.chk_folderGRTS.setObjectName("chk_folderGRTS")
        self.horizontalLayout_5.addWidget(self.chk_folderGRTS)
        self.grts_txt = QtWidgets.QLineEdit(Form)
        self.grts_txt.setEnabled(False)
        self.grts_txt.setMinimumSize(QtCore.QSize(200, 0))
        self.grts_txt.setMaximumSize(QtCore.QSize(200, 200))
        self.grts_txt.setObjectName("grts_txt")
        self.horizontalLayout_5.addWidget(self.grts_txt)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setEnabled(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.grts_folder = QtWidgets.QRadioButton(Form)
        self.grts_folder.setEnabled(False)
        self.grts_folder.setObjectName("grts_folder")
        self.horizontalLayout_5.addWidget(self.grts_folder)
        self.grts_folder2x = QtWidgets.QRadioButton(Form)
        self.grts_folder2x.setEnabled(False)
        self.grts_folder2x.setObjectName("grts_folder2x")
        self.horizontalLayout_5.addWidget(self.grts_folder2x)
        self.grts_folder3x = QtWidgets.QRadioButton(Form)
        self.grts_folder3x.setEnabled(False)
        self.grts_folder3x.setObjectName("grts_folder3x")
        self.horizontalLayout_5.addWidget(self.grts_folder3x)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setStyleSheet("font: italic;\n"
"color: rgb(191, 191, 191);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chk_sitename_folder = QtWidgets.QCheckBox(Form)
        self.chk_sitename_folder.setObjectName("chk_sitename_folder")
        self.horizontalLayout_6.addWidget(self.chk_sitename_folder)
        self.site_text = QtWidgets.QLineEdit(Form)
        self.site_text.setEnabled(False)
        self.site_text.setMinimumSize(QtCore.QSize(200, 0))
        self.site_text.setMaximumSize(QtCore.QSize(200, 200))
        self.site_text.setObjectName("site_text")
        self.horizontalLayout_6.addWidget(self.site_text)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setEnabled(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.site_folder = QtWidgets.QRadioButton(Form)
        self.site_folder.setEnabled(False)
        self.site_folder.setObjectName("site_folder")
        self.horizontalLayout_6.addWidget(self.site_folder)
        self.site_folder2x = QtWidgets.QRadioButton(Form)
        self.site_folder2x.setEnabled(False)
        self.site_folder2x.setObjectName("site_folder2x")
        self.horizontalLayout_6.addWidget(self.site_folder2x)
        self.site_folder3x = QtWidgets.QRadioButton(Form)
        self.site_folder3x.setEnabled(False)
        self.site_folder3x.setObjectName("site_folder3x")
        self.horizontalLayout_6.addWidget(self.site_folder3x)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setStyleSheet("font: italic;\n"
"color: rgb(191, 191, 191);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeview_original = QtWidgets.QTreeView(self.groupBox)
        self.treeview_original.setObjectName("treeview_original")
        self.verticalLayout.addWidget(self.treeview_original)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeview_changed = QtWidgets.QTreeView(self.groupBox_2)
        self.treeview_changed.setObjectName("treeview_changed")
        self.verticalLayout_2.addWidget(self.treeview_changed)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_4.addWidget(self.btn_save)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.progressBar_tarball = QtWidgets.QProgressBar(Form)
        self.progressBar_tarball.setProperty("value", 24)
        self.progressBar_tarball.setObjectName("progressBar_tarball")
        self.horizontalLayout_10.addWidget(self.progressBar_tarball)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.btn_tarball = QtWidgets.QPushButton(Form)
        self.btn_tarball.setObjectName("btn_tarball")
        self.horizontalLayout_10.addWidget(self.btn_tarball)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Source Directory:"))
        self.btn_browse.setText(_translate("Form", "browse"))
        self.label_12.setText(_translate("Form", "Output Directory:"))
        self.btn_browse_output.setText(_translate("Form", "browse"))
        self.label_13.setText(_translate("Form", "Optional.  Leave blank to Rename (Overwrite!) existing files."))
        self.label_6.setText(_translate("Form", "Operations are perfomed sequentially, top to bottom. View final names in right box below.  Guano MD element \'Original Filename\' is populated (or overwritten) with the original file name on renaming."))
        self.chk_auto_rename.setText(_translate("Form", "NABat Auto Correct"))
        self.label_7.setText(_translate("Form", "Remove content in square brackets, Replace non-letters and numbers with underscores, Remove duplicate underscores, Remove non-digit prefixes, Remove trailing counts (_001) ."))
        self.chk_replace.setText(_translate("Form", "String Replace   "))
        self.label_2.setText(_translate("Form", "with"))
        self.chk_use_re.setText(_translate("Form", "Use RE"))
        self.label_8.setText(_translate("Form", "Replace specific text with something, or leave second box empty to delete.  Use RE option to use regular expressions."))
        self.chk_replace2.setText(_translate("Form", "String Replace 2"))
        self.label_3.setText(_translate("Form", "with"))
        self.chk_use_re2.setText(_translate("Form", "Use RE"))
        self.label_9.setText(_translate("Form", "Replace specific text with something, or leave second box empty to delete.  Use RE option to use regular expressions."))
        self.chk_folderGRTS.setText(_translate("Form", "GRTS ID is:   "))
        self.label_4.setText(_translate("Form", "or"))
        self.grts_folder.setText(_translate("Form", "Parent Folder"))
        self.grts_folder2x.setText(_translate("Form", "Parent Folder 2x"))
        self.grts_folder3x.setText(_translate("Form", "Parent Folder 3x"))
        self.label_10.setText(_translate("Form", "Specify a GRTS ID.  Last three underscore separated elements are retained."))
        self.chk_sitename_folder.setText(_translate("Form", "Site Name is:"))
        self.label_5.setText(_translate("Form", "or"))
        self.site_folder.setText(_translate("Form", "Parent Folder"))
        self.site_folder2x.setText(_translate("Form", "Parent Folder 2x"))
        self.site_folder3x.setText(_translate("Form", "Parent Folder 3x"))
        self.label_11.setText(_translate("Form", "Specify a Site Name.  First and last two underscore separated elements are retained."))
        self.groupBox.setTitle(_translate("Form", "Original"))
        self.groupBox_2.setTitle(_translate("Form", "Renamed"))
        self.btn_save.setText(_translate("Form", "Rename Files"))
        self.btn_tarball.setText(_translate("Form", "Create tarball"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

